### ISSUE TITLE
Camera parameters setting in Objaverse rendering

### ISSUE THREAD

**Issue by YuanxunLu** [MV-Dream/MVDream#10]
Hi, 

Thanks for your impressive work!  I'm currently working on rendering the Objaverse dataset using your provided settings. However, I have encountered some confusion regarding the descriptions in Section 4.1:

> For each object, we first normalize the object to be at the center, and then choose a random camera distance between [0.9, 1.1], fov between [15, 60] and elevation between [0, 30].

and here are my questions:

1. Regarding the **camera distance**, when you mention a random value between [0.9, 1.1], could you please clarify its exact meaning? Does it refer to the camera radius, implying that the camera is positioned on a sphere with the center at (0, 0, 0)? From my understanding, after scene normalization, the scene's bounding box would range in [-0.5, 0.5] along the XYZ axes. Kindly correct me if I'm mistaken.
2. The **fov** is randomly chosen in [15, 60]. I am concerned that fov=15 might be too small to capture the entire scene. However, in Fig. 5 (top two rows) of your paper, the training images appear to have been rendered with a relatively larger fov.  I attempted to render the same scene with different fov values and found that only when using **camera radius=1.1, fov=60** could generate a similar rendering in Fig. 5. The rendering script I used was modified from the Zero123 repo.

The following three results from left to right, rendered with a **camera radius of 1.1 and fov of 15, 40, and 60** respectively, are depicted below:
![030-concat](https://github.com/MV-Dream/MVDream/assets/35017815/9e6f6a8a-091a-4230-a82c-356c2474e0aa)
and this is a screenshot of Fig.5 (Top Right) in the paper for reference:
![171695203496_ pic](https://github.com/MV-Dream/MVDream/assets/35017815/262d1e6b-f8ca-4bf8-aec4-41e813d87c93)

I noticed that only **fov=60** produces a similar rendering. However, this value represents the upper limit of the sampling parameters, implying that most sampled fov values would result in incomplete renderings. Could you clarify if this is true for your rendering dataset? Or maybe there are any bugs in my rendering code?

Thanks again for your amazing work and look forward to your feedback!

**Comment by seasonSH** [comment]
Good question. The paper did not explain this part clearly. The camera radius here actually refers to a relative scale to the focal length so that the objects appear with a similar size regardless of fov.
More formally, it is like this:
1. sample fov ~ U(15,64)
2. sample relative radius from r ~ U(0.9,1.1)
3. camera distance = r * focal

Thanks for mentioning this and we will clarify it in the paper.

**Comment by YuanxunLu** [comment]
Thanks for your prompt reply! That makes really clear!
