### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by yhyu13** [MV-Dream/MVDream#5]
Hi, 

Is there any schedule on full release? And would it easy to integrate with existing DDC tools like Blender?

**Comment by pengwangucla** [comment]
We plan to release the nerf training this month [which is based on [threestudio](https://github.com/threestudio-project/threestudio, where a mesh like object export is supported. ]

**Comment by yhyu13** [comment]
@pengwangucla wait, maybe a stupid question. Do you mean to release MVDream with thresstudio by making a pull requestin into part of thresstudio? Or making MVDream based on thresstudio but not considered MVDream as part of thresstudio
